builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags: -tags netgo
archive:
  format: binary
release:
  github:
    owner: newscorp-ghfb
    name: okta-kubectl-auth

sign:
  signature: "${artifact}.asc"
  artifacts: checksum
  args: ["-u", "cloudengineering@news.co.uk", "--output", "${signature}", "--detach-sign", "--armor",  "${artifact}"]
